package quickbeer.android.domain.place.store

import quickbeer.android.domain.place.Place
import quickbeer.android.util.Mapper

object PlaceEntityMapper : Mapper<Place, PlaceEntity> {

    override fun mapFrom(source: Place): PlaceEntity {
        return PlaceEntity(
            id = source.id,
            brewerId = source.brewerId,
            type = source.type?.value,
            name = source.name,
            plainName = source.plainName,
            description = source.description,
            mapId = source.mapId,
            tourId = source.tourId,
            regionId = source.regionId,
            msa = source.msa,
            latitude = source.latitude,
            longitude = source.longitude,
            geoOverride = source.geoOverride,
            address = source.address,
            city = source.city,
            stateId = source.stateId,
            countryId = source.countryId,
            postalCode = source.postalCode,
            phoneNumber = source.phoneNumber,
            phoneCountryCode = source.phoneCountryCode,
            phoneAreaCode = source.phoneAreaCode,
            website = source.website,
            facebook = source.facebook,
            twitter = source.twitter,
            foodMenu = source.foodMenu,
            beerMenu = source.beerMenu,
            rating = source.rating,
            avgRating = source.avgRating,
            bayMean = source.bayMean,
            percentile = source.percentile,
            rateCount = source.rateCount,
            taps = source.taps,
            bottles = source.bottles,
            seasonals = source.seasonals,
            realAles = source.realAles,
            rareBeers = source.rareBeers,
            macros = source.macros,
            glassware = source.glassware,
            singles = source.singles,
            togo = source.togo,
            wifi = source.wifi,
            children = source.children,
            reservations = source.reservations,
            patio = source.patio,
            tv = source.tv,
            games = source.games,
            scene = source.scene,
            staff = source.staff,
            parking = source.parking,
            music = source.music,
            events = source.events,
            noise = source.noise,
            seating = source.seating,
            smoking = source.smoking,
            cigars = source.cigars,
            food = source.food,
            hours = source.hours,
            comments = source.comments,
            currency = source.currency,
            mailOrder = source.mailOrder,
            mailOrderInternational = source.mailOrderInternational,
            retired = source.retired,
            userId = source.userId,
            editedBy = source.editedBy,
            timeAdded = source.timeAdded,
            timeEdited = source.timeEdited,
            normalizedName = source.normalizedName,
            updated = source.updated,
            accessed = source.accessed
        )
    }

    override fun mapTo(source: PlaceEntity): Place {
        return Place(
            id = source.id,
            brewerId = source.brewerId,
            type = Place.Type.fromValue(source.type),
            name = source.name,
            plainName = source.plainName,
            description = source.description,
            mapId = source.mapId,
            tourId = source.tourId,
            regionId = source.regionId,
            msa = source.msa,
            latitude = source.latitude,
            longitude = source.longitude,
            geoOverride = source.geoOverride,
            address = source.address,
            city = source.city,
            stateId = source.stateId,
            countryId = source.countryId,
            postalCode = source.postalCode,
            phoneNumber = source.phoneNumber,
            phoneCountryCode = source.phoneCountryCode,
            phoneAreaCode = source.phoneAreaCode,
            website = source.website,
            facebook = source.facebook,
            twitter = source.twitter,
            foodMenu = source.foodMenu,
            beerMenu = source.beerMenu,
            rating = source.rating,
            avgRating = source.avgRating,
            bayMean = source.bayMean,
            percentile = source.percentile,
            rateCount = source.rateCount,
            taps = source.taps,
            bottles = source.bottles,
            seasonals = source.seasonals,
            realAles = source.realAles,
            rareBeers = source.rareBeers,
            macros = source.macros,
            glassware = source.glassware,
            singles = source.singles,
            togo = source.togo,
            wifi = source.wifi,
            children = source.children,
            reservations = source.reservations,
            patio = source.patio,
            tv = source.tv,
            games = source.games,
            scene = source.scene,
            staff = source.staff,
            parking = source.parking,
            music = source.music,
            events = source.events,
            noise = source.noise,
            seating = source.seating,
            smoking = source.smoking,
            cigars = source.cigars,
            food = source.food,
            hours = source.hours,
            comments = source.comments,
            currency = source.currency,
            mailOrder = source.mailOrder,
            mailOrderInternational = source.mailOrderInternational,
            retired = source.retired,
            userId = source.userId,
            editedBy = source.editedBy,
            timeAdded = source.timeAdded,
            timeEdited = source.timeEdited,
            normalizedName = source.normalizedName,
            updated = source.updated,
            accessed = source.accessed
        )
    }
}
